services:
  app:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: npm run start:dev

  postgres:
    profiles: ["dev"]
    env_file:
      - .env
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  app_e2e_test:
    profiles: ["test"]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - test_postgres
    command: npm run test:e2e

  test_postgres:
    profiles: ["test"]
    env_file:
      - .env.test
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "4999:5432"