services:
  backend:
    build:
      context: .
      target: builder-backend
    volumes:
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.dev
    networks:
      - default
      - backend_network
    restart: unless-stopped
    command: yarn start:dev

networks:
  default:
  backend_network:
    name: backend_network
    external: true
